//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadTiendaCelulares
{
    using System;
    using System.Collections.Generic;
    
    public partial class compras
    {
        public int id { get; set; }
        public string direccion_envio { get; set; }
        public decimal total { get; set; }
        public System.DateTime fecha_venta { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> idCelular { get; set; }
    
        public virtual celulares celulares { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
