//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadTiendaCelulares
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabTiendaCelularesEntities1 : DbContext
    {
        public LabTiendaCelularesEntities1()
            : base("name=LabTiendaCelularesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<celulares> celulares { get; set; }
        public virtual DbSet<colores> colores { get; set; }
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
